"""add bill_influence_signals table

Revision ID: 9d1ea29c0ea6
Revises: b94eebfdfd90
Create Date: 2026-03-28 02:10:43.230202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d1ea29c0ea6'
down_revision: Union[str, None] = 'b94eebfdfd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_influence_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rarity_pct', sa.Float(), nullable=True),
    sa.Column('rarity_label', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('baseline_rate', sa.Float(), nullable=True),
    sa.Column('observed_rate', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_influence_signals_bill_id'), 'bill_influence_signals', ['bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_influence_signals_bill_id'), table_name='bill_influence_signals')
    op.drop_table('bill_influence_signals')
    # ### end Alembic commands ###
