"""add official_influence_signals table

Revision ID: a87ed4c3a1f4
Revises: 9d1ea29c0ea6
Create Date: 2026-03-28 03:49:13.613450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a87ed4c3a1f4'
down_revision: Union[str, None] = '9d1ea29c0ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_influence_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('official_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rarity_pct', sa.Float(), nullable=True),
    sa.Column('rarity_label', sa.String(length=20), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('baseline_rate', sa.Float(), nullable=True),
    sa.Column('observed_rate', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['official_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_influence_signals_official_id'), 'official_influence_signals', ['official_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_official_influence_signals_official_id'), table_name='official_influence_signals')
    op.drop_table('official_influence_signals')
    # ### end Alembic commands ###
