"""add money_trails table

Revision ID: b94eebfdfd90
Revises: 005_add_ingestion_jobs
Create Date: 2026-03-25 04:32:38.622964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b94eebfdfd90'
down_revision: Union[str, None] = '005_add_ingestion_jobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money_trails',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('official_id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('dot_count', sa.Integer(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('chain_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('total_amount', sa.BigInteger(), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['official_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_trails_official_id'), 'money_trails', ['official_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_money_trails_official_id'), table_name='money_trails')
    op.drop_table('money_trails')
    # ### end Alembic commands ###
