"""
Comprehensive seed data for John Fetterman and related entities.
All data is realistic mock data for development purposes.
"""

MOCK_BRIEFING = """Senator John Karl Fetterman (D-PA) is the junior United States Senator from Pennsylvania, having assumed office on January 3, 2023, after defeating Republican nominee Mehmet Oz in the 2022 general election. Fetterman is a progressive Democrat known for his unconventional style and populist messaging, though he has increasingly broken with progressive orthodoxy on issues including Israel and immigration. He serves on the Senate Banking, Housing, and Urban Affairs Committee; the Agriculture, Nutrition, and Forestry Committee; and the Joint Economic Committee. His political brand centers on working-class economic populism rooted in his tenure as mayor of Braddock, a post-industrial steel town in Allegheny County.

Financial disclosure analysis reveals potential areas of interest. Fetterman holds positions in JPMorgan Chase ($1,001-$15,000) and BlackRock ($15,001-$50,000) while serving on the Senate Banking Committee, which has direct oversight jurisdiction over both firms. He also holds ExxonMobil stock ($1,001-$15,000) and NextEra Energy ($1,001-$15,000), spanning both traditional and clean energy sectors. His Pfizer holdings ($1,001-$15,000) are notable in the context of pharmaceutical pricing legislation. The largest single position is in Pennsylvania Real Estate Investment Trust ($50,001-$100,000), reflecting local economic ties. While these holdings are modest by Senate standards and largely in broad-market funds, the Banking Committee nexus with financial sector holdings warrants monitoring.

Campaign finance records show a heavily union-aligned funding base. The 2022 cycle was dominated by ActBlue-aggregated small-dollar donations ($24.5M), reflecting strong grassroots support. Major institutional backers include SEIU ($290,000), AFL-CIO ($185,000), Laborers' International Union ($175,000), AFSCME ($165,000), IBEW ($145,000), and Plumbers/Pipefitters Union ($120,000). Environmental groups including the League of Conservation Voters ($275,000) and Sierra Club ($150,000) are significant contributors. Notably, Fetterman received $35,000 from the American Bankers Association and $30,000 from the Securities Industry and Financial Markets Association, both of which fall under his Banking Committee jurisdiction. Comcast Corp, headquartered in Philadelphia, contributed $45,000.

Legislative priorities reflect a mix of populist economic policy and Pennsylvania-specific concerns. Key bills include the Fair Credit Reporting Improvement Act and Community Reinvestment Modernization Act (both Banking Committee), the Railroad Safety Enhancement Act (introduced after the East Palestine, Ohio derailment near the PA border), and the American Steel Protection Act (targeting PA's industrial base). His Cannabis Decriminalization and Expungement Act and FETTERMAN Act (targeting TikTok) reflect his higher-profile policy positions. Voting patterns show consistent alignment with Democratic leadership on major legislation, with YES votes on the Infrastructure Investment and Jobs Act, Inflation Reduction Act, CHIPS Act, and Respect for Marriage Act."""

FETTERMAN_ENTITY = {
    "slug": "john-fetterman",
    "entity_type": "person",
    "name": "John Fetterman",
    "summary": "United States Senator from Pennsylvania (D). Member of the Senate Banking, Housing, and Urban Affairs Committee; Agriculture, Nutrition, and Forestry Committee; and Joint Economic Committee. Former Lt. Governor of Pennsylvania (2019-2023) and Mayor of Braddock, PA (2006-2019).",
    "metadata": {
        "bioguideId": "F000480",
        "party": "Democrat",
        "state": "PA",
        "district": None,
        "chamber": "Senate",
        "termStart": "2023-01-03",
        "termEnd": "2029-01-03",
        "born": "1969-08-15",
        "birthPlace": "West Reading, PA",
        "education": [
            {"degree": "B.S.", "field": "Finance", "institution": "Albright College", "year": 1991},
            {"degree": "MBA", "institution": "University of Connecticut", "year": 1993},
            {"degree": "MPP", "field": "Public Policy", "institution": "Harvard Kennedy School", "year": 1999},
        ],
        "committees": [
            {"name": "Banking, Housing, and Urban Affairs", "role": "Member", "code": "SSBK"},
            {"name": "Agriculture, Nutrition, and Forestry", "role": "Member", "code": "SSAF"},
            {"name": "Joint Economic Committee", "role": "Member", "code": "JSEC"},
        ],
        "priorRoles": [
            {"title": "Lieutenant Governor of Pennsylvania", "start": "2019-01-15", "end": "2023-01-03"},
            {"title": "Mayor of Braddock, PA", "start": "2006-01-01", "end": "2019-01-14"},
        ],
        "website": "https://www.fetterman.senate.gov",
        "contact": {"office": "142 Russell Senate Office Building", "phone": "(202) 224-4254"},
        "mock_briefing": MOCK_BRIEFING,
    },
}

# ---------------------------------------------------------------------------
# HOLDINGS (companies as entities + relationships)
# ---------------------------------------------------------------------------
HOLDINGS = [
    {
        "entity": {
            "slug": "vanguard-total-stock-market-etf",
            "entity_type": "company",
            "name": "Vanguard Total Stock Market ETF (VTI)",
            "summary": "Exchange-traded fund tracking the CRSP US Total Market Index, providing broad exposure to the entire U.S. equity market.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$15,001-$50,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "Vanguard Total Stock Market ETF",
                "ticker": "VTI",
                "asset_type": "Exchange-Traded Fund",
                "value_min": 15001,
                "value_max": 50000,
                "income_type": "Dividends",
                "income_min": 201,
                "income_max": 1000,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            },
        },
    },
    {
        "entity": {
            "slug": "ishares-core-sp500-etf",
            "entity_type": "company",
            "name": "iShares Core S&P 500 ETF (IVV)",
            "summary": "Exchange-traded fund managed by BlackRock tracking the S&P 500 index.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$50,001-$100,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "iShares Core S&P 500 ETF",
                "ticker": "IVV",
                "asset_type": "Exchange-Traded Fund",
                "value_min": 50001,
                "value_max": 100000,
                "income_type": "Dividends",
                "income_min": 1001,
                "income_max": 2500,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            },
        },
    },
    {
        "entity": {
            "slug": "apple-inc",
            "entity_type": "company",
            "name": "Apple Inc",
            "summary": "Multinational technology company. Designs, manufactures, and markets consumer electronics, software, and services. Headquartered in Cupertino, CA.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$1,001-$15,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "Apple Inc",
                "ticker": "AAPL",
                "asset_type": "Stock",
                "value_min": 1001,
                "value_max": 15000,
                "income_type": "Dividends",
                "income_min": 1,
                "income_max": 200,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            },
        },
    },
    {
        "entity": {
            "slug": "microsoft-corp",
            "entity_type": "company",
            "name": "Microsoft Corp",
            "summary": "Multinational technology corporation. Develops, licenses, and supports software, services, devices, and solutions worldwide. Headquartered in Redmond, WA.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$15,001-$50,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "Microsoft Corp",
                "ticker": "MSFT",
                "asset_type": "Stock",
                "value_min": 15001,
                "value_max": 50000,
                "income_type": "Dividends",
                "income_min": 201,
                "income_max": 1000,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            },
        },
    },
    {
        "entity": {
            "slug": "jpmorgan-chase",
            "entity_type": "company",
            "name": "JPMorgan Chase & Co",
            "summary": "Multinational financial services firm and the largest bank in the United States by assets. Regulated by the Senate Banking Committee. Headquartered in New York, NY.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$1,001-$15,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "JPMorgan Chase & Co",
                "ticker": "JPM",
                "asset_type": "Stock",
                "value_min": 1001,
                "value_max": 15000,
                "income_type": "Dividends",
                "income_min": 1,
                "income_max": 200,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
                "conflict_note": "Fetterman serves on Banking Committee which has oversight jurisdiction over JPMorgan Chase",
            },
        },
    },
    {
        "entity": {
            "slug": "exxonmobil-corp",
            "entity_type": "company",
            "name": "ExxonMobil Corp",
            "summary": "Multinational oil and gas corporation. One of the largest publicly traded energy companies. Headquartered in Irving, TX.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$1,001-$15,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "ExxonMobil Corp",
                "ticker": "XOM",
                "asset_type": "Stock",
                "value_min": 1001,
                "value_max": 15000,
                "income_type": "Dividends",
                "income_min": 1,
                "income_max": 200,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            },
        },
    },
    {
        "entity": {
            "slug": "pfizer-inc",
            "entity_type": "company",
            "name": "Pfizer Inc",
            "summary": "Multinational pharmaceutical and biotechnology corporation. One of the world's largest pharmaceutical companies by revenue. Headquartered in New York, NY.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$1,001-$15,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "Pfizer Inc",
                "ticker": "PFE",
                "asset_type": "Stock",
                "value_min": 1001,
                "value_max": 15000,
                "income_type": "Dividends",
                "income_min": 1,
                "income_max": 200,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
                "conflict_note": "Relevant to pharmaceutical pricing legislation votes",
            },
        },
    },
    {
        "entity": {
            "slug": "blackrock-inc",
            "entity_type": "company",
            "name": "BlackRock Inc",
            "summary": "Multinational investment management corporation. World's largest asset manager. Regulated by the Senate Banking Committee. Headquartered in New York, NY.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$15,001-$50,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "BlackRock Inc",
                "ticker": "BLK",
                "asset_type": "Stock",
                "value_min": 15001,
                "value_max": 50000,
                "income_type": "Dividends",
                "income_min": 201,
                "income_max": 1000,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
                "conflict_note": "Fetterman serves on Banking Committee which has oversight jurisdiction over BlackRock",
            },
        },
    },
    {
        "entity": {
            "slug": "nextera-energy",
            "entity_type": "company",
            "name": "NextEra Energy Inc",
            "summary": "Energy company and the world's largest generator of renewable energy from wind and solar. Headquartered in Juno Beach, FL.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$1,001-$15,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "NextEra Energy Inc",
                "ticker": "NEE",
                "asset_type": "Stock",
                "value_min": 1001,
                "value_max": 15000,
                "income_type": "Dividends",
                "income_min": 1,
                "income_max": 200,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            },
        },
    },
    {
        "entity": {
            "slug": "pa-real-estate-investment-trust",
            "entity_type": "company",
            "name": "Pennsylvania Real Estate Investment Trust",
            "summary": "Real estate investment trust focused on retail shopping malls and power centers in the eastern United States, primarily in the Philadelphia metropolitan area.",
        },
        "relationship": {
            "relationship_type": "holds_stock",
            "amount_label": "$50,001-$100,000",
            "source_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            "source_label": "Senate EFD Annual Report 2023",
            "metadata": {
                "asset_name": "Pennsylvania Real Estate Investment Trust",
                "ticker": "PREIT",
                "asset_type": "REIT",
                "value_min": 50001,
                "value_max": 100000,
                "income_type": "Dividends",
                "income_min": 1001,
                "income_max": 2500,
                "filing_year": 2023,
                "filing_url": "https://efdsearch.senate.gov/search/view/annual/fake-001/",
            },
        },
    },
]

# ---------------------------------------------------------------------------
# CAMPAIGN DONORS (PACs, orgs, individuals as entities + relationships)
# ---------------------------------------------------------------------------
DONORS = [
    {
        "entity": {
            "slug": "seiu",
            "entity_type": "organization",
            "name": "Service Employees International Union (SEIU)",
            "summary": "Labor union representing about 2 million workers in healthcare, the public sector, and property services across the US and Canada.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 29000000,
            "amount_label": "$290,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "SEIU COPE (Committee on Political Education)",
                "contributor_type": "PAC",
                "industry_code": "P04000",
                "industry_label": "Labor Unions",
                "receipt_date": "2022-06-15",
                "transaction_id": "SA11AI.fake001",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "afl-cio",
            "entity_type": "organization",
            "name": "AFL-CIO",
            "summary": "Federation of 60 national and international labor unions representing 12.5 million working people.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 18500000,
            "amount_label": "$185,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "AFL-CIO COPE Political Contributions Committee",
                "contributor_type": "PAC",
                "industry_code": "P04000",
                "industry_label": "Labor Unions",
                "receipt_date": "2022-07-20",
                "transaction_id": "SA11AI.fake002",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "actblue",
            "entity_type": "organization",
            "name": "ActBlue",
            "summary": "Nonprofit technology organization and the largest source of funds in American politics. Serves as a conduit for small-dollar Democratic donors.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 2450000000,
            "amount_label": "$24,500,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "ActBlue (aggregated small donors)",
                "contributor_type": "PAC (Conduit)",
                "industry_code": "W06000",
                "industry_label": "Small Dollar Contributions",
                "receipt_date": "2022-11-01",
                "transaction_id": "SA11AI.fake003",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "emilys-list",
            "entity_type": "pac",
            "name": "Emily's List",
            "summary": "Political action committee that aims to help elect Democratic pro-choice women to office.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 42500000,
            "amount_label": "$425,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "EMILY's List",
                "contributor_type": "PAC",
                "industry_code": "Q01000",
                "industry_label": "Women's Issues",
                "receipt_date": "2022-08-10",
                "transaction_id": "SA11AI.fake004",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "sierra-club",
            "entity_type": "organization",
            "name": "Sierra Club",
            "summary": "Environmental organization with chapters in all 50 states. Focuses on climate, clean energy, and conservation.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 15000000,
            "amount_label": "$150,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "Sierra Club Political Committee",
                "contributor_type": "PAC",
                "industry_code": "Q11000",
                "industry_label": "Environment",
                "receipt_date": "2022-09-05",
                "transaction_id": "SA11AI.fake005",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "league-of-conservation-voters",
            "entity_type": "organization",
            "name": "League of Conservation Voters",
            "summary": "Environmental advocacy group that works to turn environmental values into national, state, and local priorities.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 27500000,
            "amount_label": "$275,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "League of Conservation Voters Action Fund",
                "contributor_type": "Super PAC",
                "industry_code": "Q11000",
                "industry_label": "Environment",
                "receipt_date": "2022-10-01",
                "transaction_id": "SA11AI.fake006",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "comcast-corp",
            "entity_type": "company",
            "name": "Comcast Corp",
            "summary": "Multinational telecommunications conglomerate headquartered in Philadelphia, PA. Parent of NBCUniversal and Sky Group.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 4500000,
            "amount_label": "$45,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "Comcast Corporation & NBCUniversal PAC",
                "contributor_type": "PAC",
                "industry_code": "B02000",
                "industry_label": "Telecom Services & Equipment",
                "receipt_date": "2022-05-15",
                "transaction_id": "SA11AI.fake007",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "american-bankers-association",
            "entity_type": "organization",
            "name": "American Bankers Association",
            "summary": "Trade association for the U.S. banking industry representing banks of all sizes. Actively lobbies on Banking Committee legislation.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 3500000,
            "amount_label": "$35,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "American Bankers Association PAC (BankPAC)",
                "contributor_type": "PAC",
                "industry_code": "F03000",
                "industry_label": "Commercial Banks",
                "receipt_date": "2022-10-15",
                "transaction_id": "SA11AI.fake008",
                "election_cycle": "2022",
                "conflict_note": "Fetterman serves on Banking Committee with jurisdiction over banking industry",
            },
        },
    },
    {
        "entity": {
            "slug": "national-association-of-realtors",
            "entity_type": "organization",
            "name": "National Association of Realtors",
            "summary": "Largest trade association in the United States representing over 1.5 million members involved in residential and commercial real estate.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 4000000,
            "amount_label": "$40,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "Realtors PAC",
                "contributor_type": "PAC",
                "industry_code": "F10000",
                "industry_label": "Real Estate",
                "receipt_date": "2022-09-20",
                "transaction_id": "SA11AI.fake009",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "alphabet-inc",
            "entity_type": "company",
            "name": "Alphabet Inc",
            "summary": "Multinational technology conglomerate and parent of Google, YouTube, and other technology businesses. Headquartered in Mountain View, CA.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 12500000,
            "amount_label": "$125,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "Alphabet Inc employees (individual contributions)",
                "contributor_type": "Individual (aggregated by employer)",
                "industry_code": "B12000",
                "industry_label": "Internet & Technology",
                "receipt_date": "2022-10-30",
                "transaction_id": "SA11AI.fake010",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "microsoft-employees-pac",
            "entity_type": "pac",
            "name": "Microsoft Corp Employees",
            "summary": "Aggregated individual political contributions from Microsoft Corp employees.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 9500000,
            "amount_label": "$95,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "Microsoft Corp employees (individual contributions)",
                "contributor_type": "Individual (aggregated by employer)",
                "industry_code": "B12000",
                "industry_label": "Computer Software",
                "receipt_date": "2022-10-25",
                "transaction_id": "SA11AI.fake011",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "university-of-pittsburgh",
            "entity_type": "organization",
            "name": "University of Pittsburgh",
            "summary": "State-related public research university in Pittsburgh, Pennsylvania. One of the largest employers in western PA.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 8500000,
            "amount_label": "$85,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "University of Pittsburgh employees (individual contributions)",
                "contributor_type": "Individual (aggregated by employer)",
                "industry_code": "W04000",
                "industry_label": "Education",
                "receipt_date": "2022-09-01",
                "transaction_id": "SA11AI.fake012",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "philadelphia-federation-of-teachers",
            "entity_type": "organization",
            "name": "Philadelphia Federation of Teachers",
            "summary": "Local union representing teachers and school employees in the School District of Philadelphia. Affiliate of AFT.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 5500000,
            "amount_label": "$55,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "Philadelphia Federation of Teachers COPE",
                "contributor_type": "PAC",
                "industry_code": "P04000",
                "industry_label": "Labor Unions - Teachers",
                "receipt_date": "2022-08-22",
                "transaction_id": "SA11AI.fake013",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "laborers-international-union",
            "entity_type": "organization",
            "name": "Laborers' International Union of North America",
            "summary": "Labor union representing construction workers, healthcare workers, postal workers, and others across the US and Canada.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 17500000,
            "amount_label": "$175,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "Laborers' Political League",
                "contributor_type": "PAC",
                "industry_code": "P04000",
                "industry_label": "Labor Unions - Building Trades",
                "receipt_date": "2022-07-10",
                "transaction_id": "SA11AI.fake014",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "plumbers-pipefitters-union",
            "entity_type": "organization",
            "name": "United Association of Plumbers and Pipefitters",
            "summary": "Labor union representing plumbers, pipefitters, sprinkler fitters, welders, and HVAC technicians in the US and Canada.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 12000000,
            "amount_label": "$120,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "UA Political Education Committee",
                "contributor_type": "PAC",
                "industry_code": "P04000",
                "industry_label": "Labor Unions - Building Trades",
                "receipt_date": "2022-06-28",
                "transaction_id": "SA11AI.fake015",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "afscme",
            "entity_type": "organization",
            "name": "American Federation of State, County and Municipal Employees",
            "summary": "Labor union representing 1.4 million public service workers in state, county, and municipal governments across the US.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 16500000,
            "amount_label": "$165,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "AFSCME PEOPLE (Public Employees Organized to Promote Legislative Equality)",
                "contributor_type": "PAC",
                "industry_code": "P04000",
                "industry_label": "Labor Unions - Public Sector",
                "receipt_date": "2022-08-01",
                "transaction_id": "SA11AI.fake016",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "sifma",
            "entity_type": "organization",
            "name": "Securities Industry and Financial Markets Association",
            "summary": "Trade association representing broker-dealers, investment banks, and asset managers. Actively lobbies on Banking Committee legislation.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 3000000,
            "amount_label": "$30,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "SIFMA PAC",
                "contributor_type": "PAC",
                "industry_code": "F07000",
                "industry_label": "Securities & Investment",
                "receipt_date": "2022-11-01",
                "transaction_id": "SA11AI.fake017",
                "election_cycle": "2022",
                "conflict_note": "SIFMA is regulated by the Banking Committee on which Fetterman serves",
            },
        },
    },
    {
        "entity": {
            "slug": "credit-union-national-association",
            "entity_type": "organization",
            "name": "Credit Union National Association",
            "summary": "Trade association representing credit unions in the United States. Advocates for credit union interests before Congress.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 2500000,
            "amount_label": "$25,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "CUNA Congressional Affairs Fund (CCAF)",
                "contributor_type": "PAC",
                "industry_code": "F03000",
                "industry_label": "Credit Unions",
                "receipt_date": "2022-10-10",
                "transaction_id": "SA11AI.fake018",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "national-education-association",
            "entity_type": "organization",
            "name": "National Education Association",
            "summary": "The largest labor union in the United States, representing public school teachers, faculty, support staff, and other education workers.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 11000000,
            "amount_label": "$110,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "NEA Fund for Children and Public Education",
                "contributor_type": "PAC",
                "industry_code": "P04000",
                "industry_label": "Labor Unions - Teachers",
                "receipt_date": "2022-09-15",
                "transaction_id": "SA11AI.fake019",
                "election_cycle": "2022",
            },
        },
    },
    {
        "entity": {
            "slug": "ibew",
            "entity_type": "organization",
            "name": "International Brotherhood of Electrical Workers",
            "summary": "Labor union representing approximately 775,000 active members and retirees in electrical construction, utilities, and telecommunications.",
        },
        "relationship": {
            "relationship_type": "donated_to",
            "amount_usd": 14500000,
            "amount_label": "$145,000",
            "date_start": "2021-01-01",
            "date_end": "2022-12-31",
            "source_url": "https://www.fec.gov/data/receipts/?committee_id=C00764126",
            "source_label": "FEC Receipts 2021-2022",
            "metadata": {
                "committee_id": "C00764126",
                "committee_name": "Fetterman for PA",
                "contributor_name": "IBEW Committee on Political Education (COPE)",
                "contributor_type": "PAC",
                "industry_code": "P04000",
                "industry_label": "Labor Unions - Electrical Workers",
                "receipt_date": "2022-07-15",
                "transaction_id": "SA11AI.fake020",
                "election_cycle": "2022",
            },
        },
    },
]

# ---------------------------------------------------------------------------
# BILLS SPONSORED
# ---------------------------------------------------------------------------
BILLS = [
    {
        "entity": {
            "slug": "s4001-fair-credit-reporting",
            "entity_type": "bill",
            "name": "S.4001 - Fair Credit Reporting Improvement Act",
            "summary": "Amends the Fair Credit Reporting Act to improve accuracy of consumer credit reports, increase accountability of credit bureaus, and protect consumers from predatory data practices.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-11-15",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/4001",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "4001",
                "type": "S",
                "title": "Fair Credit Reporting Improvement Act",
                "introducedDate": "2023-11-15",
                "latestAction": {"actionDate": "2024-01-20", "text": "Read twice and referred to the Committee on Banking, Housing, and Urban Affairs."},
                "policyArea": "Finance and Financial Sector",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/4001",
                "committees": ["Banking, Housing, and Urban Affairs"],
                "cosponsors": 4,
                "status": "Introduced",
            },
        },
    },
    {
        "entity": {
            "slug": "s2788-fetterman-act",
            "entity_type": "bill",
            "name": "S.2788 - FETTERMAN Act",
            "summary": "Fighting Emerging Threats from TikTok, Ensuring Removal of Malicious Applications, and Neutralizing. Requires divestiture of TikTok from ByteDance or face prohibition in the United States.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-09-12",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/2788",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "2788",
                "type": "S",
                "title": "FETTERMAN Act",
                "introducedDate": "2023-09-12",
                "latestAction": {"actionDate": "2023-12-05", "text": "Read twice and referred to the Committee on Commerce, Science, and Transportation."},
                "policyArea": "Science, Technology, Communications",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/2788",
                "committees": ["Commerce, Science, and Transportation"],
                "cosponsors": 8,
                "status": "Introduced",
                "bipartisan": True,
            },
        },
    },
    {
        "entity": {
            "slug": "s1234-community-reinvestment",
            "entity_type": "bill",
            "name": "S.1234 - Community Reinvestment Modernization Act",
            "summary": "Modernizes the Community Reinvestment Act to expand coverage to non-bank lenders and fintechs, strengthen enforcement, and address racial disparities in lending.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-04-20",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/1234",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "1234",
                "type": "S",
                "title": "Community Reinvestment Modernization Act",
                "introducedDate": "2023-04-20",
                "latestAction": {"actionDate": "2023-07-15", "text": "Committee on Banking, Housing, and Urban Affairs. Hearings held."},
                "policyArea": "Finance and Financial Sector",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/1234",
                "committees": ["Banking, Housing, and Urban Affairs"],
                "cosponsors": 6,
                "status": "Hearings Held",
            },
        },
    },
    {
        "entity": {
            "slug": "s3456-affordable-housing",
            "entity_type": "bill",
            "name": "S.3456 - Affordable Housing Access Act",
            "summary": "Increases funding for the Housing Trust Fund, expands Low-Income Housing Tax Credits, and creates new incentives for affordable housing construction in underserved areas.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-12-01",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/3456",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "3456",
                "type": "S",
                "title": "Affordable Housing Access Act",
                "introducedDate": "2023-12-01",
                "latestAction": {"actionDate": "2024-02-10", "text": "Read twice and referred to the Committee on Banking, Housing, and Urban Affairs."},
                "policyArea": "Housing and Community Development",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/3456",
                "committees": ["Banking, Housing, and Urban Affairs"],
                "cosponsors": 3,
                "status": "Introduced",
            },
        },
    },
    {
        "entity": {
            "slug": "s2345-clean-water-infrastructure",
            "entity_type": "bill",
            "name": "S.2345 - Clean Water Infrastructure Act",
            "summary": "Authorizes additional funding for clean water and wastewater infrastructure, prioritizing lead pipe replacement and PFAS contamination remediation in rural and underserved communities.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-07-18",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/2345",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "2345",
                "type": "S",
                "title": "Clean Water Infrastructure Act",
                "introducedDate": "2023-07-18",
                "latestAction": {"actionDate": "2023-10-05", "text": "Read twice and referred to the Committee on Environment and Public Works."},
                "policyArea": "Environmental Protection",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/2345",
                "committees": ["Environment and Public Works"],
                "cosponsors": 5,
                "status": "Introduced",
            },
        },
    },
    {
        "entity": {
            "slug": "s567-railroad-safety",
            "entity_type": "bill",
            "name": "S.567 - Railroad Safety Enhancement Act",
            "summary": "Strengthens railroad safety regulations following the East Palestine, Ohio derailment. Requires improved braking systems, increased inspections, and higher liability caps for hazardous materials carriers.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-02-28",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/567",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "567",
                "type": "S",
                "title": "Railroad Safety Enhancement Act",
                "introducedDate": "2023-02-28",
                "latestAction": {"actionDate": "2023-05-10", "text": "Committee on Commerce, Science, and Transportation. Ordered to be reported with an amendment in the nature of a substitute favorably."},
                "policyArea": "Transportation and Public Works",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/567",
                "committees": ["Commerce, Science, and Transportation"],
                "cosponsors": 12,
                "status": "Ordered Reported",
                "bipartisan": True,
            },
        },
    },
    {
        "entity": {
            "slug": "s890-cannabis-decriminalization",
            "entity_type": "bill",
            "name": "S.890 - Cannabis Decriminalization and Expungement Act",
            "summary": "Removes cannabis from the Controlled Substances Act, establishes a process for expungement of federal cannabis convictions, and creates a framework for federal regulation and taxation.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-03-20",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/890",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "890",
                "type": "S",
                "title": "Cannabis Decriminalization and Expungement Act",
                "introducedDate": "2023-03-20",
                "latestAction": {"actionDate": "2023-03-20", "text": "Read twice and referred to the Committee on the Judiciary."},
                "policyArea": "Crime and Law Enforcement",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/890",
                "committees": ["Judiciary"],
                "cosponsors": 7,
                "status": "Introduced",
            },
        },
    },
    {
        "entity": {
            "slug": "s1111-american-steel-protection",
            "entity_type": "bill",
            "name": "S.1111 - American Steel Protection Act",
            "summary": "Strengthens anti-dumping measures for steel imports, provides tax incentives for domestic steel production, and requires federal infrastructure projects to use American-made steel.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-04-05",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/1111",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "1111",
                "type": "S",
                "title": "American Steel Protection Act",
                "introducedDate": "2023-04-05",
                "latestAction": {"actionDate": "2023-06-15", "text": "Read twice and referred to the Committee on Finance."},
                "policyArea": "Commerce",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/1111",
                "committees": ["Finance"],
                "cosponsors": 4,
                "status": "Introduced",
                "bipartisan": True,
            },
        },
    },
    {
        "entity": {
            "slug": "s2222-veterans-housing",
            "entity_type": "bill",
            "name": "S.2222 - Veterans Housing Assistance Expansion Act",
            "summary": "Expands VA home loan benefits, increases funding for HUD-VASH vouchers, and creates new grant programs for veteran transitional housing.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-06-30",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/2222",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "2222",
                "type": "S",
                "title": "Veterans Housing Assistance Expansion Act",
                "introducedDate": "2023-06-30",
                "latestAction": {"actionDate": "2023-09-12", "text": "Committee on Veterans' Affairs. Hearings held."},
                "policyArea": "Armed Forces and National Security",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/2222",
                "committees": ["Veterans' Affairs"],
                "cosponsors": 9,
                "status": "Hearings Held",
                "bipartisan": True,
            },
        },
    },
    {
        "entity": {
            "slug": "s3333-farm-worker-labor-standards",
            "entity_type": "bill",
            "name": "S.3333 - Farm Worker Fair Labor Standards Act",
            "summary": "Extends overtime protections to agricultural workers, establishes heat safety standards, and creates a pathway to legal status for undocumented farmworkers.",
        },
        "relationship": {
            "relationship_type": "sponsored",
            "date_start": "2023-11-28",
            "source_url": "https://www.congress.gov/bill/118th-congress/senate-bill/3333",
            "source_label": "Congress.gov",
            "metadata": {
                "congress": 118,
                "number": "3333",
                "type": "S",
                "title": "Farm Worker Fair Labor Standards Act",
                "introducedDate": "2023-11-28",
                "latestAction": {"actionDate": "2023-11-28", "text": "Read twice and referred to the Committee on Agriculture, Nutrition, and Forestry."},
                "policyArea": "Agriculture and Food",
                "url": "https://www.congress.gov/bill/118th-congress/senate-bill/3333",
                "committees": ["Agriculture, Nutrition, and Forestry"],
                "cosponsors": 3,
                "status": "Introduced",
            },
        },
    },
]

# ---------------------------------------------------------------------------
# KEY VOTES (stored as relationships to bill entities or vote entities)
# ---------------------------------------------------------------------------
VOTES = [
    {
        "entity": {
            "slug": "infrastructure-investment-jobs-act",
            "entity_type": "bill",
            "name": "Infrastructure Investment and Jobs Act",
            "summary": "Bipartisan infrastructure law providing $1.2 trillion for transportation, broadband, water, and energy infrastructure.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-01-20",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-1", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "inflation-reduction-act",
            "entity_type": "bill",
            "name": "Inflation Reduction Act",
            "summary": "Landmark legislation addressing climate change, healthcare costs, and tax reform. Includes $369 billion in energy and climate spending.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-01-20",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-2", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "chips-and-science-act",
            "entity_type": "bill",
            "name": "CHIPS and Science Act",
            "summary": "Provides $52.7 billion in subsidies for semiconductor manufacturing and research in the United States.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-01-20",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-3", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "bipartisan-safer-communities-act",
            "entity_type": "bill",
            "name": "Bipartisan Safer Communities Act",
            "summary": "Gun safety legislation enhancing background checks for buyers under 21, funding crisis intervention programs, and closing the boyfriend loophole.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-02-15",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-4", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "respect-for-marriage-act",
            "entity_type": "bill",
            "name": "Respect for Marriage Act",
            "summary": "Federal law requiring the U.S. federal government and all states to recognize the validity of same-sex and interracial marriages.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-03-01",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-5", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "electoral-count-reform-act",
            "entity_type": "bill",
            "name": "Electoral Count Reform Act",
            "summary": "Reforms the Electoral Count Act to clarify the Vice President's ministerial role in certifying election results and raise objection thresholds.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-03-15",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-6", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "railway-safety-act",
            "entity_type": "bill",
            "name": "Railway Safety Act",
            "summary": "Bipartisan legislation introduced after the East Palestine derailment to improve rail safety, increase inspections, and strengthen hazmat regulations.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-05-20",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-7", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "restrict-act",
            "entity_type": "bill",
            "name": "RESTRICT Act",
            "summary": "Legislation to address threats from technology products and services from foreign adversaries, including potential TikTok restrictions.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-06-10",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-8", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "debt-limit-suspension",
            "entity_type": "bill",
            "name": "Fiscal Responsibility Act (Debt Limit Suspension)",
            "summary": "Suspended the debt ceiling through January 2025 while imposing discretionary spending caps and clawing back unspent COVID relief funds.",
        },
        "relationship": {
            "relationship_type": "voted_yes",
            "date_start": "2023-06-01",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "YES", "vote_number": "118-1-9", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "secure-the-border-act",
            "entity_type": "bill",
            "name": "Secure the Border Act",
            "summary": "Republican border security bill requiring completion of the border wall, reinstating Remain in Mexico policy, and increasing border patrol funding.",
        },
        "relationship": {
            "relationship_type": "voted_no",
            "date_start": "2023-09-15",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "NO", "vote_number": "118-1-10", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "tax-cuts-extension",
            "entity_type": "bill",
            "name": "Tax Cuts and Jobs Act Extension",
            "summary": "Proposal to make permanent the individual tax cuts from the 2017 Tax Cuts and Jobs Act, including lower marginal rates and increased standard deduction.",
        },
        "relationship": {
            "relationship_type": "voted_no",
            "date_start": "2023-10-01",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {"vote": "NO", "vote_number": "118-1-11", "congress": 118, "session": 1},
        },
    },
    {
        "entity": {
            "slug": "pharmaceutical-price-cap-act",
            "entity_type": "bill",
            "name": "Pharmaceutical Price Cap Act",
            "summary": "Proposed legislation to cap out-of-pocket prescription drug costs and expand Medicare drug price negotiation authority beyond the Inflation Reduction Act.",
        },
        "relationship": {
            "relationship_type": "voted_no",
            "date_start": "2023-11-10",
            "source_url": "https://www.senate.gov/legislative/LIS/roll_call_votes/",
            "source_label": "Senate Roll Call Vote",
            "metadata": {
                "vote": "NO",
                "vote_number": "118-1-12",
                "congress": 118,
                "session": 1,
                "conflict_note": "Fetterman voted NO on expanded pharma price caps while holding Pfizer stock ($1,001-$15,000)",
            },
        },
    },
]


# ---------------------------------------------------------------------------
# COMMITTEES (as entities + relationships)
# ---------------------------------------------------------------------------
COMMITTEES = [
    {
        "entity": {
            "slug": "senate-banking-committee",
            "entity_type": "organization",
            "name": "Senate Banking, Housing, and Urban Affairs Committee",
            "summary": "Standing committee of the United States Senate with jurisdiction over banking, insurance, financial markets, securities, housing, urban development, and mass transit.",
        },
        "relationship": {
            "relationship_type": "committee_member",
            "date_start": "2023-01-03",
            "source_url": "https://www.banking.senate.gov/about/membership",
            "source_label": "Senate Banking Committee",
            "metadata": {"role": "Member", "code": "SSBK", "congress": 118},
        },
    },
    {
        "entity": {
            "slug": "senate-agriculture-committee",
            "entity_type": "organization",
            "name": "Senate Agriculture, Nutrition, and Forestry Committee",
            "summary": "Standing committee of the United States Senate with jurisdiction over agriculture, food policy, nutrition programs, forestry, and rural development.",
        },
        "relationship": {
            "relationship_type": "committee_member",
            "date_start": "2023-01-03",
            "source_url": "https://www.agriculture.senate.gov/about/membership",
            "source_label": "Senate Agriculture Committee",
            "metadata": {"role": "Member", "code": "SSAF", "congress": 118},
        },
    },
    {
        "entity": {
            "slug": "joint-economic-committee",
            "entity_type": "organization",
            "name": "Joint Economic Committee",
            "summary": "Joint committee of the United States Congress that provides economic research and analysis to Congress.",
        },
        "relationship": {
            "relationship_type": "committee_member",
            "date_start": "2023-01-03",
            "source_url": "https://www.jec.senate.gov/public/index.cfm/members",
            "source_label": "Joint Economic Committee",
            "metadata": {"role": "Member", "code": "JSEC", "congress": 118},
        },
    },
]


# ---------------------------------------------------------------------------
# LOBBYING (company -> bill lobbying relationships for evidence chains)
# ---------------------------------------------------------------------------
LOBBYING_RELATIONSHIPS = [
    {
        "company_slug": "jpmorgan-chase",
        "bill_slug": "s4001-fair-credit-reporting",
        "metadata": {
            "lobbying_firm": "Capitol Bridge Partners",
            "total_spend": "$2,400,000",
            "issues": ["Credit reporting reform", "Consumer data privacy"],
            "source": "LDA Filing",
        },
    },
    {
        "company_slug": "jpmorgan-chase",
        "bill_slug": "s1234-community-reinvestment",
        "metadata": {
            "lobbying_firm": "JPMorgan Government Relations",
            "total_spend": "$1,800,000",
            "issues": ["Community reinvestment requirements", "CRA modernization"],
            "source": "LDA Filing",
        },
    },
    {
        "company_slug": "blackrock-inc",
        "bill_slug": "s4001-fair-credit-reporting",
        "metadata": {
            "lobbying_firm": "Covington & Burling",
            "total_spend": "$950,000",
            "issues": ["Financial regulation", "Credit market oversight"],
            "source": "LDA Filing",
        },
    },
    {
        "company_slug": "exxonmobil-corp",
        "bill_slug": "infrastructure-investment-jobs-act",
        "metadata": {
            "lobbying_firm": "ExxonMobil Government Relations",
            "total_spend": "$3,200,000",
            "issues": ["Energy infrastructure", "Pipeline permitting"],
            "source": "LDA Filing",
        },
    },
    {
        "company_slug": "pfizer-inc",
        "bill_slug": "s3456-affordable-housing",
        "metadata": {
            "lobbying_firm": "Pfizer Government Relations",
            "total_spend": "$1,100,000",
            "issues": ["Healthcare access in affordable housing", "Community health"],
            "source": "LDA Filing",
        },
    },
    {
        "company_slug": "microsoft-corp",
        "bill_slug": "infrastructure-investment-jobs-act",
        "metadata": {
            "lobbying_firm": "Microsoft Government Affairs",
            "total_spend": "$2,800,000",
            "issues": ["Broadband infrastructure", "Digital equity"],
            "source": "LDA Filing",
        },
    },
]


# ---------------------------------------------------------------------------
# REVOLVING DOOR (lobbyists who formerly held government positions)
# ---------------------------------------------------------------------------
REVOLVING_DOOR = [
    {
        "lobbyist": {
            "name": "Marcus Webb",
            "entity_type": "person",
            "slug": "marcus-webb",
            "metadata": {
                "former_role": "Chief of Staff, Senate Banking Committee",
                "left_government": "2021-06-15",
                "current_employer": "Capitol Bridge Partners",
                "lobbies_for": ["JPMorgan Chase", "Goldman Sachs", "Citigroup"],
                "registration_url": "https://lda.senate.gov/filings/mock-001",
            },
        },
        "former_position": "Chief of Staff, Senate Banking Committee (2017-2021)",
        "current_role": "Senior Partner, Capitol Bridge Partners",
        "lobbies_committee": "Banking, Housing, and Urban Affairs",
        "clients": ["JPMorgan Chase", "Goldman Sachs", "Citigroup"],
        "relationship_type": "revolving_door_lobbyist",
        "why_this_matters": "Marcus Webb spent 4 years as the top aide on the Banking Committee. He knew every senator's priorities, had their personal cell numbers, and understood exactly how deals got made. Now JPMorgan Chase pays him to walk back into those same offices and ask for favors. The access he has isn't something money can buy — he got it from years of government service.",
    },
    {
        "lobbyist": {
            "name": "Sarah Chen-Watkins",
            "entity_type": "person",
            "slug": "sarah-chen-watkins",
            "metadata": {
                "former_role": "Legislative Director, Sen. Fetterman's Office",
                "left_government": "2024-01-10",
                "current_employer": "Harvest Policy Group",
                "lobbies_for": ["Cargill", "Archer Daniels Midland"],
                "registration_url": "https://lda.senate.gov/filings/mock-002",
            },
        },
        "former_position": "Legislative Director, Office of Sen. Fetterman (2023-2024)",
        "current_role": "Vice President, Harvest Policy Group",
        "lobbies_committee": "Agriculture, Nutrition, and Forestry",
        "clients": ["Cargill", "Archer Daniels Midland"],
        "relationship_type": "revolving_door_lobbyist",
        "why_this_matters": "Sarah Chen-Watkins wrote policy for Senator Fetterman on agriculture issues. Less than a year after leaving his office, she's now lobbying that same office on behalf of two of the biggest agricultural companies in the world. She knows exactly what arguments will work because she used to be the one deciding which arguments mattered.",
    },
    {
        "lobbyist": {
            "name": "David Thornton",
            "entity_type": "person",
            "slug": "david-thornton",
            "metadata": {
                "former_role": "General Counsel, Senate Banking Committee",
                "left_government": "2022-03-01",
                "current_employer": "PhRMA (Pharmaceutical Research and Manufacturers of America)",
                "lobbies_for": ["Pfizer", "Johnson & Johnson", "Merck"],
                "registration_url": "https://lda.senate.gov/filings/mock-003",
            },
        },
        "former_position": "General Counsel, Senate Banking Committee (2019-2022)",
        "current_role": "Director of Government Affairs, PhRMA",
        "lobbies_committee": "Banking, Housing, and Urban Affairs",
        "clients": ["Pfizer", "Johnson & Johnson", "Merck"],
        "relationship_type": "revolving_door_lobbyist",
        "why_this_matters": "David Thornton was the Banking Committee's top lawyer — he literally helped write the rules that govern how pharmaceutical companies can raise capital and price their drugs. Now Big Pharma pays him to influence those exact same rules. He's not just a lobbyist — he helped build the system he's now trying to change.",
    },
]

# ---------------------------------------------------------------------------
# FAMILY FINANCIAL CONNECTIONS (spouse/dependent income sources)
# ---------------------------------------------------------------------------
FAMILY_CONNECTIONS = [
    {
        "family_member": "Gisele Barreto Fetterman (spouse)",
        "relationship_to_official": "spouse",
        "employer": {
            "name": "JPMorgan Chase",
            "slug": "jpmorgan-chase",
            "entity_type": "company",
        },
        "role": "Senior Community Development Consultant",
        "annual_income": 185000,
        "relationship_type": "spouse_income_from",
        "committee_overlap": "Banking, Housing, and Urban Affairs",
        "why_this_matters": "Senator Fetterman's wife earns $185,000 a year from JPMorgan Chase. He sits on the Banking Committee — the committee that decides the rules JPMorgan has to follow. That means his family's income literally depends on a company he's supposed to be holding accountable. Can he be truly tough on JPMorgan when his wife's paycheck comes from them?",
    },
    {
        "family_member": "Gisele Barreto Fetterman (spouse)",
        "relationship_to_official": "spouse",
        "employer": {
            "name": "Fetterman Foundation",
            "slug": "fetterman-foundation",
            "entity_type": "organization",
        },
        "role": "Executive Director",
        "annual_income": 95000,
        "relationship_type": "family_employed_by",
        "committee_overlap": None,
        "why_this_matters": "The Fetterman Foundation is a family-run nonprofit. While there's no direct conflict with his committee work, foundations can receive donations from corporations and individuals who have business before the Senate. Worth watching who donates to the foundation.",
    },
]

# ---------------------------------------------------------------------------
# SPEAKING FEES & OUTSIDE INCOME
# ---------------------------------------------------------------------------
OUTSIDE_INCOME = [
    {
        "payer": {
            "name": "Financial Services Roundtable",
            "slug": "financial-services-roundtable",
            "entity_type": "organization",
            "metadata": {"industry": "financial_services", "is_lobbying_org": True},
        },
        "income_type": "speaking_fee",
        "amount_usd": 75000,
        "date": "2025-03-15",
        "event": "Annual Policy Summit 2025",
        "relationship_type": "speaking_fee_from",
        "regulated_industry": True,
        "committee_overlap": "Banking, Housing, and Urban Affairs",
        "why_this_matters": "The Financial Services Roundtable is a lobbying group for the biggest banks in America. They paid Senator Fetterman $75,000 for one speech. He sits on the committee that writes the rules those banks have to follow. That's more than most Americans earn in a year — for a couple hours of talking. The question isn't whether it's legal (it is). The question is: when those banks need a vote, does this payment cross his mind?",
    },
    {
        "payer": {
            "name": "HarperCollins Publishers",
            "slug": "harpercollins-publishers",
            "entity_type": "company",
            "metadata": {"industry": "media", "parent_company": "News Corp"},
        },
        "income_type": "book_deal",
        "amount_usd": 200000,
        "date": "2024-11-01",
        "event": "Book advance: 'From Braddock to the Senate'",
        "relationship_type": "book_deal_with",
        "regulated_industry": True,
        "committee_overlap": None,
        "why_this_matters": "HarperCollins is owned by News Corp — Rupert Murdoch's media empire. A $200,000 book deal is a significant payment from a major media conglomerate. While publishing isn't directly under his committee's jurisdiction, media companies have plenty of business before the Senate (antitrust, FCC regulation, tax policy). Book deals are a perfectly legal way for corporations to put money in a politician's pocket.",
    },
    {
        "payer": {
            "name": "University of Pittsburgh",
            "slug": "university-of-pittsburgh",
            "entity_type": "organization",
            "metadata": {"industry": "education", "type": "public_university"},
        },
        "income_type": "honorarium",
        "amount_usd": 15000,
        "date": "2025-06-20",
        "event": "Commencement Address",
        "relationship_type": "outside_income_from",
        "regulated_industry": False,
        "committee_overlap": None,
        "why_this_matters": "A $15,000 speaking fee from a public university is relatively modest and doesn't overlap with his committee work. This is the kind of outside income that rarely raises eyebrows — included here for completeness.",
    },
]

# ---------------------------------------------------------------------------
# GOVERNMENT CONTRACT PATTERNS (contractor-donor connections)
# ---------------------------------------------------------------------------
CONTRACTOR_DONORS = [
    {
        "contractor": {
            "name": "Keystone Infrastructure Group",
            "slug": "keystone-infrastructure-group",
            "entity_type": "company",
            "metadata": {"state": "PA", "industry": "construction", "employees": 2400},
        },
        "donation_amount": 25000,
        "donation_date": "2023-09-15",
        "contract_amount": 12000000,
        "contract_date": "2024-02-20",
        "contract_agency": "Department of Transportation",
        "contract_description": "Highway bridge replacement, I-76 corridor, Montgomery County PA",
        "relationship_type": "contractor_donor",
        "why_this_matters": "Keystone Infrastructure donated $25,000 to Senator Fetterman's campaign. Five months later, they landed a $12 million federal contract to fix bridges in Pennsylvania. Did the donation help them get the contract? Maybe not directly — but companies don't donate to politicians for fun. They do it because access matters when billion-dollar contracts are on the line. The donation was 0.2% of the contract value. Pretty good return on investment if there's any connection at all.",
    },
    {
        "contractor": {
            "name": "PennTech Solutions",
            "slug": "penntech-solutions",
            "entity_type": "company",
            "metadata": {"state": "PA", "industry": "technology", "employees": 800},
        },
        "donation_amount": 15000,
        "donation_date": "2024-01-10",
        "contract_amount": 8500000,
        "contract_date": "2024-08-05",
        "contract_agency": "Department of Veterans Affairs",
        "contract_description": "Electronic health records modernization, Philadelphia VA Medical Center",
        "relationship_type": "contractor_donor",
        "why_this_matters": "PennTech Solutions donated $15,000 to the campaign, then got an $8.5 million VA contract seven months later. The VA's tech modernization has been plagued by cost overruns nationwide. When a company donates to the senator from their state and then wins a federal contract in that state, it's worth asking: was this the best bid, or did connections help?",
    },
    {
        "contractor": {
            "name": "Commonwealth Health Partners",
            "slug": "commonwealth-health-partners",
            "entity_type": "company",
            "metadata": {"state": "PA", "industry": "healthcare", "employees": 5200},
        },
        "donation_amount": 40000,
        "donation_date": "2023-06-01",
        "contract_amount": 22000000,
        "contract_date": "2024-04-15",
        "contract_agency": "Department of Health and Human Services",
        "contract_description": "Rural healthcare expansion program, Western Pennsylvania",
        "relationship_type": "contractor_donor",
        "why_this_matters": "This is the biggest pattern in the set: $40,000 in donations followed by a $22 million federal healthcare contract. Commonwealth Health Partners is a major employer in Western PA — Fetterman's home turf. Rural healthcare is genuinely important, but when the company writing the biggest campaign checks also gets the biggest contracts, the public deserves to know. That's $550 in contract value for every $1 donated.",
    },
]

# ---------------------------------------------------------------------------
# INSIDER TIMING ANALYSIS (stock trade timing vs committee activity)
# ---------------------------------------------------------------------------
INSIDER_TIMING = [
    {
        "stock": "Pfizer",
        "stock_slug": "pfizer",
        "transaction_type": "sell",
        "transaction_date": "2025-01-08",
        "amount_range": "$15,001-$50,000",
        "days_before_committee_hearing": 12,
        "hearing_topic": "Drug Pricing Reform Act markup session",
        "hearing_date": "2025-01-20",
        "days_before_related_vote": 28,
        "vote_topic": "Drug Pricing Reform Act floor vote",
        "vote_date": "2025-02-05",
        "information_access_score": 9,
        "pattern_flag": "TRADE_BEFORE_HEARING",
        "stock_movement_after": "-14.2%",
        "pattern_description": "Sold up to $50,000 in Pfizer stock 12 days before his own committee held a markup session on drug pricing that sent pharma stocks tumbling 14%.",
        "why_this_matters": "Senator Fetterman sold his Pfizer stock less than two weeks before his own committee took action that crushed pharma stock prices. If he'd held onto it, he would have lost up to $7,000. Was it a lucky guess? Maybe. But he literally sits in the room where these decisions get made. He knew the hearing was coming. He knew what the committee was planning. Regular investors didn't.",
    },
    {
        "stock": "JPMorgan Chase",
        "stock_slug": "jpmorgan-chase",
        "transaction_type": "buy",
        "transaction_date": "2024-11-15",
        "amount_range": "$1,001-$15,000",
        "days_before_committee_hearing": 18,
        "hearing_topic": "Federal Reserve interest rate policy oversight",
        "hearing_date": "2024-12-03",
        "days_before_related_vote": None,
        "vote_topic": None,
        "vote_date": None,
        "information_access_score": 7,
        "pattern_flag": "BUY_BEFORE_FAVORABLE",
        "stock_movement_after": "+8.3%",
        "pattern_description": "Bought JPMorgan stock 18 days before a Banking Committee hearing where favorable interest rate policy was discussed. Bank stocks rose 8.3% after.",
        "why_this_matters": "He bought bank stock right before his committee held a hearing that was good news for banks. Banking Committee members often get private briefings before public hearings. They know what witnesses will say, what questions will be asked, and what direction policy is heading — before anyone else does. The stock went up 8.3% after the hearing. Nice timing.",
    },
    {
        "stock": "ExxonMobil",
        "stock_slug": "exxonmobil",
        "transaction_type": "sell",
        "transaction_date": "2025-03-01",
        "amount_range": "$1,001-$15,000",
        "days_before_committee_hearing": 7,
        "hearing_topic": "Climate and clean energy infrastructure markup",
        "hearing_date": "2025-03-08",
        "days_before_related_vote": 35,
        "vote_topic": "Clean Energy Transition Act",
        "vote_date": "2025-04-05",
        "information_access_score": 8,
        "pattern_flag": "TRADE_BEFORE_HEARING",
        "stock_movement_after": "-11.7%",
        "pattern_description": "Sold ExxonMobil stock just 7 days before a committee hearing on clean energy that hammered oil stocks.",
        "why_this_matters": "Seven days. That's how long before the clean energy hearing he dumped his oil stock. The hearing led to legislation that's bad news for fossil fuel companies — ExxonMobil dropped nearly 12% afterward. He's on the committee that scheduled the hearing. He knew it was coming. He knew what it was about. And he sold before the bad news hit.",
    },
]

INSIDER_TIMING_SUMMARY = {
    "total_trades_analyzed": 12,
    "trades_within_30_days_of_hearing": 5,
    "trades_before_favorable_outcome": 3,
    "trades_before_unfavorable_outcome": 2,
    "average_information_access_score": 7.2,
    "overall_pattern": "5 of 12 stock trades occurred within 30 days of a related committee hearing. In 3 cases, the trade direction (buy/sell) aligned with the outcome that would benefit the senator financially. This pattern is stronger than random chance would predict.",
    "why_this_matters": "Members of Congress trade stocks while having access to information that regular investors don't. Senator Fetterman's trades show a pattern: almost half happened right before his own committee took action on related issues. Each trade alone could be a coincidence. But when you see the same pattern over and over — selling before bad news, buying before good news — it raises a question that deserves an answer.",
}


def get_all_seed_data():
    """Return all seed data organized for insertion."""
    return {
        "fetterman": FETTERMAN_ENTITY,
        "holdings": HOLDINGS,
        "donors": DONORS,
        "bills": BILLS,
        "votes": VOTES,
        "committees": COMMITTEES,
        "lobbying": LOBBYING_RELATIONSHIPS,
        "revolving_door": REVOLVING_DOOR,
        "family_connections": FAMILY_CONNECTIONS,
        "outside_income": OUTSIDE_INCOME,
        "contractor_donors": CONTRACTOR_DONORS,
        "insider_timing": INSIDER_TIMING,
        "insider_timing_summary": INSIDER_TIMING_SUMMARY,
    }
